[package]
name = "portal-router"
version = "0.0.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
screeps-game-api = "0.20"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }

[features]
default = []
